### ISSUE TITLE
Dúvida implementação

### ISSUE THREAD

**Issue by LucasMonari** [DaviAragao/cprime#2]
No implementação do algoritmo de teste, a operações abaixo não seriam equivalentes a:

```
			// aux = (s ^ 2) mod mersenneNumber
			mpz_powm_ui(aux, s, (long)(2), mersenneNumber); 

			// s = aux - 2
			mpz_sub_ui(s, aux, (long)(2)); 
```

No pseudo-código de exemplo disponível no Wikipedia, a subtração de 2 é feita antes do módulo pelo número de mersenne.
https://en.wikipedia.org/wiki/Lucas%E2%80%93Lehmer_primality_test

Isto não pode intervir no resultado do teste?

**Comment by LucasMonari** [comment]
Fiz uns testes usando a implementação abaixo, fazendo a subtração antes do módulo e evitando fazer o cálculo do módulo quando não for necessário. Houve uma melhora no tempo de execução evitando a operação de "módulo" quando possível. 

```
		for (i = 1; i <= expoente - 2; i++)
		{
			// aux = (s ^ 2) mod mersenneNumber
			// mpz_powm_ui(aux, s, (long)(2), mersenneNumber); 

			// s = aux - 2
			// mpz_sub_ui(s, aux, (long)(2)); 

			// aux = s ^ 2
			mpz_pow_ui(aux, s, (long)(2));
			// aux = aux - 2
			mpz_sub_ui(aux, aux, (long) 2);

			// Don't calc mod if not needed
			// if (aux > mersenneNumber)
			if (mpz_cmp(aux, mersenneNumber) >= 0) {
				// s = aux mod mesenneNumber
				mpz_mod(s, aux, mersenneNumber);
			} else {
				// s = aux
				mpz_set(s, aux);
			}
		}
```

**Comment by DaviAragao** [comment]
Até 2^281227 não interferiu o módulo sendo realizado antes da subtração.
https://apimos.herokuapp.com/getLastMersenne
https://apimos.herokuapp.com/getLastCalculating
https://apimos.herokuapp.com/getLastCalculated

Pode ser que até agora o -2 não fez diferença em nenhum resto.

Essa verificação é interessante e útil. Quanto maior for o expoente mais iterações vão ser necessárias para o módulo fazer alguma diferença.

Estou escrevendo o TCC. Sinta-se livre para fazer pull request.

**Comment by LucasMonari** [comment]
Favor liberar acesso de escrita ao repositório, não estou conseguindo criar uma branch.

**Comment by DaviAragao** [comment]
Você precisaria fazer um fork do projeto e criar um braço no fork. Depois fazer o pull request.

Te adicionei como colaborador no projeto. Assim você vai conseguir sem precisar do fork.

**Comment by DaviAragao** [comment]
#3
